# Generated by Django 4.0 on 2021-12-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_alter_recommendation_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_email',
            field=models.EmailField(max_length=254, verbose_name='Email do Indicado'),
        ),
    ]
