# Generated by Django 4.0 on 2021-12-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_balance_alter_user_birth_date_and_more"),
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="has_accepted",
            field=models.BooleanField(
                default=False, verbose_name="Aceitou a indicação?"
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="recommended_email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email do Indicado"
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="Usuário Indicador",
            ),
        ),
    ]
